name: Test the bot
on: push
jobs:
  Launch:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install pip requirements
        run: |
          pip3 install -r requirements.txt
      - name: Start bot
        run: |
          python3 test.py
        env:
          GUILD_ID: ${{ secrets.GUILD_ID }} 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
          PTERO_ADMIN_KEY: ${{ secrets.PTERO_ADMIN_KEY }} 
          ROLE_NAME: ${{ secrets.ROLE_NAME }} 